"""empty message

Revision ID: 1eb2d6dcbf8b
Revises: b6ea2d9bba1f
Create Date: 2023-12-20 13:00:10.614060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb2d6dcbf8b'
down_revision = 'b6ea2d9bba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_betables_budget_id_budgets')),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_betables_expense_id_expenses')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('betables')
    # ### end Alembic commands ###
